services:
  - type: web
    name: siete-octavos
    env: static
    buildCommand: "npm run build"
    outputDirectory: "build"
    redirects:
      - source: /.*
        destination: /index.html
        status: 200
